### ISSUE TITLE
Non-UTF-8 code starting with '\x8b' in file 

### ISSUE THREAD

**Issue by comemoon** [amchii/encryptpy#2]
An error occurred after the py file was encrypted:SyntaxError: Non-UTF-8 code starting with '\x8b' in file, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by amchii** [comment]
Just convert your .py file to utf-8 encoding or declare it by adding the line "# -*- coding: \<your coding\> -*-". Please search for more details if you like.
